// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ2dvm3Xe7Qm56FGC_hPHlWHttW4Z8DZE',
    appId: '1:188304203191:web:c1d7487c4208dfe006dc32',
    messagingSenderId: '188304203191',
    projectId: 'inventory-management-2480f',
    authDomain: 'inventory-management-2480f.firebaseapp.com',
    storageBucket: 'inventory-management-2480f.firebasestorage.app',
    measurementId: 'G-EFS4N6ES6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMOcEcYHDDlShK8HJn37mdv2pdIZvMUkI',
    appId: '1:188304203191:android:aff3932ec228153406dc32',
    messagingSenderId: '188304203191',
    projectId: 'inventory-management-2480f',
    storageBucket: 'inventory-management-2480f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2PoiCqAYWY5VqTAozNTf8z1RdKLhbXY',
    appId: '1:188304203191:ios:d20097462dbaf73a06dc32',
    messagingSenderId: '188304203191',
    projectId: 'inventory-management-2480f',
    storageBucket: 'inventory-management-2480f.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2PoiCqAYWY5VqTAozNTf8z1RdKLhbXY',
    appId: '1:188304203191:ios:d20097462dbaf73a06dc32',
    messagingSenderId: '188304203191',
    projectId: 'inventory-management-2480f',
    storageBucket: 'inventory-management-2480f.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ2dvm3Xe7Qm56FGC_hPHlWHttW4Z8DZE',
    appId: '1:188304203191:web:2a69fb4124b15e9b06dc32',
    messagingSenderId: '188304203191',
    projectId: 'inventory-management-2480f',
    authDomain: 'inventory-management-2480f.firebaseapp.com',
    storageBucket: 'inventory-management-2480f.firebasestorage.app',
    measurementId: 'G-DWP3N7P0HF',
  );
}
